#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__.'/bootstrap.php';

use Chinstrap\Core\Console\Runner;
use Chinstrap\Core\Kernel\ContainerFactory;
use Chinstrap\Core\Kernel\Kernel;

$container = (new ContainerFactory())();
$kernel = new Kernel($container);
$kernel->bootstrap();
$runner = (new Runner($container))();
